# Generated by Django 5.2.6 on 2025-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('ts_utc', models.DateTimeField()),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hum_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
